name: BlockBreakSounds
version: '1.0'
main: com.gotze.blockbreaksounds.Main
api-version: '1.21.4'
commands:
  blockbreaksounds:
    description: Set a sound to play whenever you break a block
    usage: /blockbreaksounds
    aliases: bbs